name: EBRO
description: "An electric bill reader and optimizer."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^3.0.3
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  fl_chart: ^0.70.2
  google_mlkit_text_recognition: ^0.14.0
  permission_handler: ^11.3.1
  provider: ^6.1.2
  flutter_scalable_ocr: ^2.2.1
  dio: ^5.1.1
  flutter_dotenv: ^5.2.1
  markdown_widget: ^2.3.2+6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true
  assets:
    - assets/.env
    - assets/lang/en.json
    - assets/lang/ur.json
    - assets/lang/ar.json